# Generated by Django 3.1.4 on 2021-01-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('message', models.CharField(max_length=264)),
            ],
        ),
    ]
