# Generated by Django 3.1.4 on 2021-01-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=128)),
                ('StudentEmail', models.EmailField(max_length=128)),
                ('Phonenumber', models.CharField(max_length=128)),
                ('Address', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=100)),
                ('Course', models.CharField(max_length=128)),
                ('Date_Enrolled', models.DateField(blank=True, null=True)),
                ('Graduation_Date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
