# Generated by Django 3.1.4 on 2021-01-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0003_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='StudentEmail',
            field=models.EmailField(max_length=128, unique=True),
        ),
    ]
