# Generated by Django 3.1.4 on 2021-01-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0005_auto_20210120_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoldLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=128)),
                ('StudentEmail', models.EmailField(max_length=128, unique=True)),
                ('Phonenumber', models.CharField(max_length=128)),
                ('Address', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=100)),
                ('Course', models.CharField(max_length=128)),
                ('Date_Enrolled', models.CharField(max_length=100)),
                ('Graduation_Date', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
